pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // run mvn inside the folder that contains pom.xml
                dir('sample-java-maven-project') {
                    bat 'mvn -B clean package'
                }
            }
        }

        stage('Run') {
            steps {
                dir('sample-java-maven-project') {
                    // Finds jar and runs it (Windows)
                    bat '''
                    for %%f in (target\\*.jar) do (
                        echo Running %%f
                        java -jar %%f
                    )
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'BUILD SUCCESS'
        }
        failure {
            echo 'BUILD FAILED'
        }
    }
}
