pipeline {
    agent any
    stages {
        stage('Checkout') { steps { checkout scm } }
        stage('Build') { steps { bat 'mvn clean package' } }
        stage('Run') { steps { bat 'for %%f in (target\\*.jar) do java -jar %%f' } }
    }
    post { success { echo 'BUILD SUCCESS' } failure { echo 'BUILD FAILED' } }
}
